## data construstion
# COCO2017      |---annotations |--person_keypoints_train2017.json
#                               |--person_keypoints_val2017.json
#               |---test2017  
#               |---train2017
#               |---val2017

COCO2017_DATASET:
  DIR : 'F:/Data/COCO2017'
  # DIR : '/media/sparc/Data/nqthinh/COCO2017
  TRAIN_ANNOTATIONS : '/media/sparc/Data/nqthinh/COCO2017/annotations/person_keypoints_train2017.json'
  VAL_ANNOTATIONS: '/media/sparc/Data/nqthinh/COCO2017/annotations/person_keypoints_val2017.json'
  TEST : '/media/sparc/Data/nqthinh/COCO2017/test2017'
  TRAIN: '/media/sparc/Data/nqthinh/COCO2017/train2017'
  VAL: '/media/sparc/Data/nqthinh/COCO2017/val2017'

INFANT_DATASET:
  TRAIN_ANNOTATIONS : '/media/sparc/Data/nqthinh/COCO2017/annotations/person_keypoints_train2017.json'
  VAL_ANNOTATIONS: '/media/sparc/Data/nqthinh/COCO2017/annotations/person_keypoints_val2017.json'
  TEST : '/media/sparc/Data/nqthinh/COCO2017/test2017'
  TRAIN: '/media/sparc/Data/nqthinh/COCO2017/train2017'
  VAL: '/media/sparc/Data/nqthinh/COCO2017/val2017'

TRAINING: 
  DATASET: 'COCO'
  EPOCH : 75
  NUM_WORKER : 4
  BATCH_SIZE : 16
  PRINT_FREQ : 50
  CHECKPOINT_FREQ : 20
  PRETRAINED_WEIGHT: './models/model_weights/mobilenet_sgd_68.848.pth.tar'
  TRANSFER_WEIGHT: None

MODEL:
  MODEL_TYPE: 'VGG19'
